# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 17:02
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Активность')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Если оставить пустым - заполнится автоматом', max_length=255, populate_from='title', unique=True)),
                ('text', models.TextField(blank=True, default=None, null=True, verbose_name='Текст')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
